name: Sync to new code

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Mirror push to target repository
      env:
        GIT_USER: rahulhm
        GIT_TOKEN: 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
      run: |
        git remote add target https://${GIT_USER}:${GIT_TOKEN}@github.com/rahulhm/evitey-deploy.git
        git push --mirror target
