
name: Sync to new code

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Mirror push to target repository
      #env:
      #  GIT_USER: rahulhm
      #  GIT_TOKEN: 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
      run: |
        git clone -b main https://rahulhm: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@github.com/rahulhm/start-stopAZ.git
        cd start-stopAZ
        git remote add target https://rahulhm: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@github.com/rahulhm/evitey-deploy.git
        git push target main
